### PR TITLE
Change damage logic

### PR DESCRIPTION
**Pull request by Nattgew**
The logic for the CHT and mixture damage were previously discussed [on the forums](http://www.fseconomy.net/forum/xplane-10/6485-mixture-cht-damage). The server applies whatever the plugin sends, and the plugin does not differentiate between aircraft types. The CHT and mixture damage do not make sense for turbine aircraft, and in the case of mixture damage, there is an actual (virtual) cost to the owner at 100-hr check time. It's simple to write a plugin to reduce mixture below the damage threshold (which I have done), but this is not obvious or accessible to all users. Also, I recently got a CL30 that insists on pegging the mixture at 1.0, which overrides the plugin workaround. :fearful:

I updated the function here to take into account the engine type, applying new rules for turbine aircraft, and leaving the old rules for anything else. Mixture damage is applied at low altitudes as a representation of contamination, but could be changed/removed if that seems unrealistic. CHT damage is based on the ITT limits, which may not always be reliable, but this damage doesn't have any tangible effect on the airplane (since "cylinder compression" readings have no effect here, as far as I know).

I also made some minor spelling/punctuation changes.

### CODE REVIEW

**Comment by Teddii** [comment]
Hi,

is there any prove from BoD, that the engine damage, that the client is sending, is taken into account for 100hr-check bills or anything like that?

As far as I know the damage data are simpy ignored on the server side.

Cheers,
Teddii

**Comment by Nattgew** [comment]
[Jimmy indicated](http://www.fseconomy.net/forum/xplane-10/6485-mixture-cht-damage#35890) (if I am not misunderstanding) that the server system wasn't designed with anything but small pistons in mind, so it just applies to each engine whatever damage the plugin reports to it.

My first 100-hr check before I started changing mixture had a charge for it. My last one, keeping mixture controlled, showed up clean. I've also seen other turbines with the charge. See the last check on N-476FO.

**Comment by Teddii** [comment]
I had in my mind that the extra costs for 100hr checks were only random and the damage values are ignored by the server .... but it reads different in the forums now, so I might be wrong.
As sais before: it can't be wrong to fix this!

The only "problem" is, that I was also working for some weeks on the next update and we should try to merge both updates together.
I think it would be best to merge your update with the master now and I'll merge my changes with the new master afterwards.
We can go into a new testing phase for a week or so before releasing it to make sure everything still works a expected.

You might also want to ask Airboss about adding you to the forum section "FSE XPlane Client Development" to discuss the changes you made with the BoD before releasing them to the public.

**Comment by Nattgew** [comment]
I don't mind merging my changes into yours, whatever works best. Looking forward to seeing your new update. Thanks for your work on this.

How should I go about contacting Airboss for that?

**Comment by Teddii** [comment]
I would suggest to contact him by PM and explaining the story to him.

I'm looking forward to see your changes in action!

**Pull request merged**
